<h2>数据科学导论第四周学习要点</h2>
<h3>1. 学习内容：NumPy基础</h3>
<h3>2. 参考资料：</h3>

* 教材：《利用Python进行数据分析（第二版）》第4章

* 扩展阅读：https://docs.scipy.org/doc/numpy/user/quickstart.html

<h3>3. 学习要点</h3>

* NumPy核心数据结构`ndarray`的基本概念
 * 注意`ndarray`与Python内置数据类型`list`的区别
* `ndarray`的创建
 * 相关函数：`np.array()`、`np.ones()`、`np.zeros()`、`np.empty()`等，更多参考<font color='blue'>教材表4-1</font>
 * 相关属性：`ndim`、`shape`、`dtype`等
* `ndarray`的类型与类型转换
 * 数据类型描述：<font color='blue'>教材表4-2</font>
 * 类型转换函数：`astype()`，应特别注意转换过程中的数据截断问题（浮点数与整数之间、字符串与数字之间）
* `ndarray`的代数运算
 * 采用与标量元素类似的方式完成多维数组的元素（element-wise）操作
 * 与传统Python代码的区别：通过向量化（vectorization）的方式避免了`for`循环
 * 更多内容参考<font color='blue'>扩展阅读的"Basic Operations"章节</font>
* 数据基本的索引和切片
 * 与Python列表的<font color='red'>重要区别</font>：数据切片是原数据的一个视图<font color='red'>view</font>，而非拷贝<font color='red'>copy</font>对于切片上的任何操作都会反映在原数据上。在实际的编程实践中，非常容易在这一点上出错。如果希望数据切片是原数据上的一份拷贝，应显式地调用`copy()`函数。有关view和copy的区别可以参考<font color='blue'>扩展阅读的”Copies and Views“章节</font>。下面考虑一个例子：

In [1]:
import numpy as np
arr = np.arange(10)
print(arr)
arr_slice = arr[5:8] # 选取一个切片，注意该切片为原数据的视图
arr_slice[0] = 1234
print(arr) # 原数据索引为5的值发生了改变
arr_slice1 = arr[1:3].copy() # 拷贝出一个切片
arr_slice1[0] = 1234
print(arr) # 原数据索引为1的值没有发生了改变

[0 1 2 3 4 5 6 7 8 9]
[   0    1    2    3    4 1234    6    7    8    9]
[   0    1    2    3    4 1234    6    7    8    9]


 * 数据切片的方式1：与Python的列表类型类似，可以通过索引进行切片，<font color='blue'>教材图4-2</font>给出了一个直观的例子
 * 数据切片的方式2：布尔型索引，即通过布尔型数组对数据进行切片，详见下例：

In [2]:
names = np.array(['Bob','Joe','Bob','Alice'])
data = np.random.randn(4,5)
print(names=='Bob') # names=='Bob'会返回一个布尔型的数组
print(data[names == 'Bob']) # 通过布尔型的数组进行切片
print(names!='Bob') # names!='Bob'会返回一个布尔型的数组
print(data[names != 'Bob']) # 通过布尔型的数组进行切片
print((names=='Bob')|(names=='Alice')) # 可以考虑多个条件
print(data[(names=='Bob')|(names=='Alice')]) # 通过布尔型的数组进行切片

data[data<0] = 0 # 通过布尔型切片选出所有的负数，统一置为0
print(data)

[ True False  True False]
[[ 2.02248626  0.13262617 -0.08818443 -1.11351768 -0.49429216]
 [-1.2288198   0.10691251  1.79953693  0.53557812  1.18659191]]
[False  True False  True]
[[ 0.18527494  1.52745882 -1.72430046 -0.58647369 -1.63378386]
 [ 0.05747092  0.41378297 -0.82192411 -0.65367479 -0.87146304]]
[ True False  True  True]
[[ 2.02248626  0.13262617 -0.08818443 -1.11351768 -0.49429216]
 [-1.2288198   0.10691251  1.79953693  0.53557812  1.18659191]
 [ 0.05747092  0.41378297 -0.82192411 -0.65367479 -0.87146304]]
[[2.02248626 0.13262617 0.         0.         0.        ]
 [0.18527494 1.52745882 0.         0.         0.        ]
 [0.         0.10691251 1.79953693 0.53557812 1.18659191]
 [0.05747092 0.41378297 0.         0.         0.        ]]


 * 花式索引（Fancy Indexing）:直接传入整数数组进行切片
 * 转置、坐标轴交换与改变`ndarray`的shape
  * 转置操作`T`
  * `reshape()`函数经常被用到，注意与前面的slice类似，它也返回一个view而非copy
  * 注意`reshape()`函数与`resize()`函数的区别

In [3]:
arr = np.random.rand(12)
print('arr', arr)
arr1 = arr.reshape(3,4)
print('arr1',arr1)
arr1[2,3] = 1234
print('arr', arr) # 原数组也会修改
arr.resize(6,2)
print('arr', arr) 

arr [0.06114683 0.00189281 0.19440762 0.59374482 0.29101727 0.6735553
 0.2538582  0.39791115 0.79603501 0.59426864 0.41286524 0.05234036]
arr1 [[0.06114683 0.00189281 0.19440762 0.59374482]
 [0.29101727 0.6735553  0.2538582  0.39791115]
 [0.79603501 0.59426864 0.41286524 0.05234036]]
arr [6.11468347e-02 1.89281236e-03 1.94407617e-01 5.93744823e-01
 2.91017267e-01 6.73555298e-01 2.53858197e-01 3.97911153e-01
 7.96035007e-01 5.94268637e-01 4.12865243e-01 1.23400000e+03]
arr [[6.11468347e-02 1.89281236e-03]
 [1.94407617e-01 5.93744823e-01]
 [2.91017267e-01 6.73555298e-01]
 [2.53858197e-01 3.97911153e-01]
 [7.96035007e-01 5.94268637e-01]
 [4.12865243e-01 1.23400000e+03]]


* 通用函数（`ufunc`）：对`ndarray`进行元素级操作的函数，调用方式上与标量数据上函数的方式类似，可以简单理解为对数组元素执行批量操作
 * 一元函数与二元函数列表分别参考<font color='blue'>教材表4-3和表4-4</font>
* <font color='red'>面向数组编程（Array-Oriented Programming）</font>：编程思路的转变
 * 将逻辑操作转换为数组运算：`np.where(cond, x, y)`函数
 * 基于`ndarray`计算统计量，详细的函数参考<font color='blue'>教材表4-5</font>
 * 布尔型数组附加的函数`any()`和`all()`
 * `ndarray`中元素的排序：`sort()`与`np.sort()`。应注意：与数据切片不同，`np.sort()`返回原数据的一份<font color='red'>拷贝</font>，而非视图，详见下例：

In [4]:
arr = np.random.randn(10)
print(arr)
arr_sorted = np.sort(arr)
arr_sorted[0]=1234
print(arr_sorted)
print(arr)

[-1.10061793 -1.51269587 -0.76722169 -2.22829701  0.1593673   0.8063429
  0.14400054  0.16406231  0.59327961 -0.11316387]
[ 1.23400000e+03 -1.51269587e+00 -1.10061793e+00 -7.67221689e-01
 -1.13163872e-01  1.44000538e-01  1.59367296e-01  1.64062313e-01
  5.93279613e-01  8.06342895e-01]
[-1.10061793 -1.51269587 -0.76722169 -2.22829701  0.1593673   0.8063429
  0.14400054  0.16406231  0.59327961 -0.11316387]


 * 集合操作：`unique()`、`intersect1d()`、`union1d()`，详细参考<font color='blue'>教材表4-6</font>
* `ndarray`的文件操作，掌握函数`save()`、`savez()`和`load()`
* 矩阵运算函数参考<font color='blue'>教材表4-7</font>
* 生成由随机数构成的`ndarray`，相关函数在机器学习参数初始化的过程中被广泛应用

<h3>4. 课后练习</h3>

* __第1题：创建一个8*8的二维ndarray 对象`A`（即为一个矩阵）。要求：`A`为上三角矩阵，矩阵每一行的非0元素形成一步长为2的递增等差数列，且对角线上元素从上到下为1, 19, 37, 55, 73, 91, 109, 127。__

In [9]:
# 请在此处写第1题的代码
import numpy as np
A = np.triu(np.arange(1, 128, 2).reshape(8,8))
A

array([[  1,   3,   5,   7,   9,  11,  13,  15],
       [  0,  19,  21,  23,  25,  27,  29,  31],
       [  0,   0,  37,  39,  41,  43,  45,  47],
       [  0,   0,   0,  55,  57,  59,  61,  63],
       [  0,   0,   0,   0,  73,  75,  77,  79],
       [  0,   0,   0,   0,   0,  91,  93,  95],
       [  0,   0,   0,   0,   0,   0, 109, 111],
       [  0,   0,   0,   0,   0,   0,   0, 127]])

* __第2题：针对下面给出的8*9的 ndarray 对象`P`做如下操作：首先，对`P`右上角8*8的子矩阵`Q`的第1行的第1个元素赋值为3；然后，将该子矩阵`Q`的各行根据最后一列的元素从小到大进行排序；最后，将矩阵`Q`与矩阵`P`左上角8*8的子矩阵相加得到矩阵`B`，并打印出来。__

In [10]:
P = np.array([[3,6,9,11,5,2,6,99,1],
              [2,4,8,10,1,3,5,7,65],
              [1,5,7,9,2,4,6,8,10],
              [4,5,3,1,7,45,7,2,0], 
              [32,5,4,8,1,7,2,0,23], 
              [5,3,8,1,4,33,62,4,9], 
              [3,6,7,1,9,47,39,1,2],
              [3,5,7,2,5,9,1,1,5]])
P

array([[ 3,  6,  9, 11,  5,  2,  6, 99,  1],
       [ 2,  4,  8, 10,  1,  3,  5,  7, 65],
       [ 1,  5,  7,  9,  2,  4,  6,  8, 10],
       [ 4,  5,  3,  1,  7, 45,  7,  2,  0],
       [32,  5,  4,  8,  1,  7,  2,  0, 23],
       [ 5,  3,  8,  1,  4, 33, 62,  4,  9],
       [ 3,  6,  7,  1,  9, 47, 39,  1,  2],
       [ 3,  5,  7,  2,  5,  9,  1,  1,  5]])

In [38]:
# 请在此处写第2题的代码
Q = P[:, 1:].copy()
Q[0,0] = 3
Q = Q[Q[:, -1].argsort()]
B = np.add(Q, P[:, :-1])
B

array([[  8,   9,  10,  18,  50,   9,   8,  99],
       [  5,  13,  19,  15,   3,   9, 104,   8],
       [  7,  12,   8,  18,  49,  43,   7,  10],
       [  9,  12,   5,   6,  16,  46,   8,   7],
       [ 35,  13,   5,  12,  34,  69,   6,   9],
       [ 10,  10,  17,   3,   8,  39,  70,  14],
       [  8,  10,  15,   2,  16,  49,  39,  24],
       [  7,  13,  17,   3,   8,  14,   8,  66]])

* __第3题：求上面得到的矩阵`A`和矩阵`B`的积，得到矩阵`C`，请打印出矩阵`C`。然后，对矩阵C的每一列做正则化，得到矩阵`D`并打印出来。__
 * 正则的概念：假设a是数组中的一个元素，max/min分别是数组元素的最大最小值，则正则化后a = (a - min)/(max - min)）。

In [39]:
# 请在此处写第3题的代码
C = np.dot(A, B)
C

array([[  755,   744,   824,   407,  1138,  2470,  1862,  1759],
       [ 2043,  2063,  2190,  1333,  3232,  6765,  5726,  3868],
       [ 3164,  2936,  2901,  1752,  5271, 10754,  5958,  5796],
       [ 4009,  3420,  3549,  1502,  4770, 12635,  7795,  7346],
       [ 4474,  3496,  4138,  1492,  4946, 12841,  9323,  8769],
       [ 2319,  3075,  4557,   744,  2976,  9436, 10757,  9776],
       [ 1649,  2533,  3522,   551,  2632,  6895,  5139,  9942],
       [  889,  1651,  2159,   381,  1016,  1778,  1016,  8382]])

In [49]:
C = C.T
D = np.zeros((len(C), len(C[0])))
for i in range(len(C)):
    max_value = C[i].max()
    min_value = C[i].min()
    D[i] = (C[i] - min_value) / (max_value - min_value)
D = D.T
D

array([[0.        , 0.        , 0.        , 0.01896426, 0.02867215,
        0.06255085, 0.0868494 , 0.        ],
       [0.34632966, 0.47928779, 0.36592553, 0.69438366, 0.52079906,
        0.45078189, 0.48352325, 0.25772944],
       [0.64775477, 0.79651163, 0.55638896, 1.        , 1.        ,
        0.81135316, 0.50734011, 0.49333985],
       [0.87496639, 0.97238372, 0.72997589, 0.81765135, 0.88225617,
        0.98137937, 0.69592444, 0.68275694],
       [1.        , 1.        , 0.88775784, 0.8103574 , 0.92361927,
        1.        , 0.85278719, 0.85665404],
       [0.42054316, 0.84702035, 1.        , 0.26477024, 0.46063455,
        0.6922173 , 1.        , 0.97971404],
       [0.2403872 , 0.65007267, 0.7227431 , 0.12399708, 0.37978848,
        0.46253277, 0.4232625 , 1.        ],
       [0.03603119, 0.32957849, 0.35762122, 0.        , 0.        ,
        0.        , 0.        , 0.80936087]])

* __第4题：对于下列ndarray对象`students`，每一列的含义分别是：名，姓，年龄，入学日期。请打印出姓`Smith`并且年龄大于`14`岁的同学的入学日期。__

In [26]:
data = np.array([['Bob', 'Smith', '12', '2019-02-01'], 
                ['Joe', 'Lawrence', '13', '2018-03-07'], 
                ['Roy', 'Ratner', '12', '2019-02-05'],
                ['Rita', 'Smith', '14', '2017-02-16'],
                ['Alice', 'Holmes', '11', '2020-02-29'], 
                ['Wool', 'Smith', '15', '2016-02-14']])
data

array([['Bob', 'Smith', '12', '2019-02-01'],
       ['Joe', 'Lawrence', '13', '2018-03-07'],
       ['Roy', 'Ratner', '12', '2019-02-05'],
       ['Rita', 'Smith', '14', '2017-02-16'],
       ['Alice', 'Holmes', '11', '2020-02-29'],
       ['Wool', 'Smith', '15', '2016-02-14']], dtype='<U10')

In [10]:
# 请在此处写第4题的代码
data[(data[:,1] == 'Smith') & (data[:,2].astype(int) > 14)][0,3]

* __第5题：利用numpy数组实现Game of Life。用一个15*15的矩阵表示225个细胞：元素取值为`1`表示活细胞，取值为`0`表示死细胞。Game of Life的过程如下：初始矩阵为`K`(如下所示)，表示细胞的初始状态；进而按照以下规则进行迭代，更新细胞状态。请你打印出迭代`100`次之后得到的矩阵__
 * 每个细胞死或活的状态由它周围的八个细胞，称为__邻居__，所决定。
 * “人口过少”：任何活细胞如果活邻居少于2个，则死掉。
 * “正常”：任何活细胞如果活邻居为2个或3个，则继续活。
 * “人口过多”：任何活细胞如果活邻居大于3个，则死掉。
 * “繁殖”：任何死细胞如果活邻居正好是3个，则活过来。

In [51]:
K = np.array([[0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1],
              [1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
              [0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0],
              [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1],
              [1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0],
              [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0],
              [1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
              [1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
              [0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0],
              [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0],
              [0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1],
              [0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
              [1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1],
              [0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0],
              [1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0]]) 
K

array([[0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0],
       [0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0]])

In [52]:
# 请在此处写第5题的代码
for nums in range(100): 
    M = K.copy()
    for row in range(len(K)):
        for line in range(len(K[0])):
            count = 0
            for i in range(-1, 2):
                for j in range(-1, 2):
                    if i == 0 and j == 0:
                        continue
                    if (row + i < 0) or (row + i > len(K) - 1) or (line + j < 0) or (line + j > len(K[0]) - 1):
                        continue
                    if M[row + i][line + j] == 1:
                        count += 1
            if M[row][line] == 1 and (count < 2 or count > 3):
                K[row][line] = 0
            if M[row][line] == 0 and count == 3:
                K[row][line] = 1
K

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [53]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
                 Z[1:-1,0:-2]                + Z[1:-1,2:] +
                 Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1) 
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

for i in range(100): 
    K = iterate(K)
print(K)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
